// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vendingbackend.Infrastructure.DataAccess;

#nullable disable

namespace vendingbackend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209160426_AddedUserPasswordHash")]
    partial class AddedUserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vendingbackend.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgDailySales")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MinimalStock")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("vendingbackend.Core.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApparatusId")
                        .HasColumnType("integer");

                    b.Property<int>("PayType")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApparatusId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales", t =>
                        {
                            t.HasCheckConstraint("CK_TotalPrice_NonNegative", "\"TotalPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("vendingbackend.Core.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApparatusId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Problems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApparatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("vendingbackend.Core.Models.TradeApparatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CheckedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryOfManufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateCreated")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateUpdated")
                        .HasColumnType("date");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InventarizationTime")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastCheckDate")
                        .HasColumnType("date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextCheckDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("date")
                        .HasComputedColumnSql("CASE WHEN \"LastCheckDate\" IS NULL THEN NULL ELSE \"LastCheckDate\" + (\"NextCheckInterval\" * INTERVAL '1 month') END", true);

                    b.Property<int>("NextCheckInterval")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("NextRepairDate")
                        .HasColumnType("date");

                    b.Property<long>("RepairTime")
                        .HasColumnType("bigint");

                    b.Property<long>("Resource")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SerialNumber")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SummaryIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("TradeApparatus", t =>
                        {
                            t.HasCheckConstraint("CK_DateUpdated_Range", "\"DateUpdated\" IS NULL OR (\"DateUpdated\" >= \"DateCreated\" AND \"DateUpdated\" <= CURRENT_DATE)");

                            t.HasCheckConstraint("CK_InventarizationTime_Range", "\"InventarizationTime\" IS NULL OR (\"InventarizationTime\" >= \"DateCreated\" AND \"InventarizationTime\" <= CURRENT_DATE)");

                            t.HasCheckConstraint("CK_LastCheckDate_Range", "\"LastCheckDate\" IS NULL OR (\"LastCheckDate\" >= \"DateCreated\" AND \"LastCheckDate\" <= CURRENT_DATE)");

                            t.HasCheckConstraint("CK_NextCheckInterval_NonNegative", "\"NextCheckInterval\" >= 0");

                            t.HasCheckConstraint("CK_NextRepairDate_Future", "\"NextRepairDate\" IS NULL OR \"NextRepairDate\" > CURRENT_DATE");

                            t.HasCheckConstraint("CK_RepairTime_Range", "\"RepairTime\" BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_Resource_Positive", "\"Resource\" > 0");
                        });
                });

            modelBuilder.Entity("vendingbackend.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("vendingbackend.Core.Models.Sales", b =>
                {
                    b.HasOne("vendingbackend.Core.Models.TradeApparatus", "Apparatus")
                        .WithMany("Sales")
                        .HasForeignKey("ApparatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vendingbackend.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparatus");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("vendingbackend.Core.Models.Service", b =>
                {
                    b.HasOne("vendingbackend.Core.Models.TradeApparatus", "Apparatus")
                        .WithMany("Services")
                        .HasForeignKey("ApparatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vendingbackend.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vendingbackend.Core.Models.TradeApparatus", b =>
                {
                    b.HasOne("vendingbackend.Core.Models.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId");

                    b.Navigation("CheckedByUser");
                });

            modelBuilder.Entity("vendingbackend.Core.Models.TradeApparatus", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
